name: Create development builds

on:
  pull_request_labeled:
    labels:
      - build-android

jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: preview
